#!/bin/bash

dir=$1
RESULT='ls -a $dir'
declare -a ARRAY
let count=0
let soft=0
for FILE in $RESULT
do
    if [ -f "$dir/$FILE" ]
     then
	 echo "$dir/$FILE is a regular file."
	 for ((i=count-1; i!=-1; i--))
	 do
	    cmp "$dir/$FILE" "${ARRAY[$i]}" -s
        	if [ $? == 0 ]
	      	then
		     	rm "$dir/$FILE"								        
        		ln ${ARRAY[$i]} "$dir/$FILE"				        	           let sof =1
			break
		fi
	 done
         if [$soft=0 ]
	 then
	     	ARRAY[$count]="$dir/$FILE"
        	let count= count+1
	 fi
   else
         echo" $dir/$FILE is NOT a regular file."
   fi
done

echo "There are $count regular files"
								 
